auth:
  rootUser: "root"
  rootPassword: "rootroot"
  username: "root"
  password: "rootroot"
  database: "project"

service:
  nameOverride: mongodb
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  size: 8Gi
  accessModes:
    - ReadWriteOnce

metrics:
  enabled: false