apiVersion: apps/v1
kind: Deployment
metadata:
  name: joffeapp
  namespace: default
  labels:
    app.kubernetes.io/instance: joffeapp
    app.kubernetes.io/name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: joffeapp
      app.kubernetes.io/name: flaskapp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: joffeapp
        app.kubernetes.io/name: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: joffe2001/playlist-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: MONGODB_URI
          value: "mongodb://root:rootroot@mongodb:27017/"
        - name: MONGODB_SERVER
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: "project"
        - name: MONGODB_USER
          value: "root"
        - name: MONGODB_PASSWORD
          value: "rootroot"