apiVersion: batch/v1
kind: Job
metadata:
  name: joffeapp-flaskapp-sanity-check-{{ .Release.Revision }}
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: flaskapp-sanity-check
        image: "joffe2001/playlist-app:latest"
        command: ["python"]
        args: ["sanity_check.py"]
      restartPolicy: Never
  backoffLimit: 4