apiVersion: v1
kind: Service
metadata:
  name: joffeapp
  namespace: default
  labels:
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: joffeapp
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: joffeapp
    meta.helm.sh/release-namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: joffeapp