apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
=======
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
stringData:
  admin.password: $2a$12$QzROjD8O3lqMxjnZ.4Di4uETxsU.qTTiv89fj5DTtTGwChnRHDhEa